/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mie_TpmVerifier */

#ifndef _Included_mie_TpmVerifier
#define _Included_mie_TpmVerifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mie_TpmVerifier
 * Method:    verify
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mie_TpmVerifier_verify
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
