/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mie_crypto_PorterStemmer */

#ifndef _Included_mie_crypto_PorterStemmer
#define _Included_mie_crypto_PorterStemmer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mie_crypto_PorterStemmer
 * Method:    stem
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_mie_crypto_PorterStemmer_stem
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
