#!/bin/bash

OUTPUT=$PWD"/output"
DATASET=$PWD"/datasets"
SCRIPTS=$PWD"/scripts"

stat $DATASET > /dev/null 2>&1
if [ "$?" != 0 ]; then
	echo "The dataset dir was not found. Exiting"
	exit 1
fi

stat $OUTPUT > /dev/null 2>&1
if [ "$?" != 0 ]; then
	echo "The output directory was not found, creating it."
	mkdir logs
fi

stat $SCRIPTS > /dev/null 2>&1
if [ "$?" != 0 ]; then
	echo "The $SCRIPTS directory was not found. Exiting"
	exit 1
fi

docker run --rm --net=host --name=client -v $OUTPUT":/output" -v $DATASET":/datasets" -v $SCRIPTS":/scripts" mie_client custom "$@"