#!/bin/bash

backend=""
cache=true

while [ "$1" != "" ]; do
    if [ "$1" == "depsky" ] || [ "$1" == "ramcloud" ]; then
        backend="$1"
        shift
    elif [ "$1" == "nocache" ]; then
        cache=false
        shift
    else
        echo "Unrecognized option: ""$1"
        exit
    fi
done

if [ "$backend" == "" ]; then
    echo "Unrecognized backend"
    exit
fi

if [ "$backend" == "depsky" ]; then
    if [ "$cache" == true ]; then
        docker run --rm --net=host --name=server mie mc mw depsky testbench2
    else
        docker run --rm --net=host --name=server mie mw depsky nocache testbench2
    fi
else
    if [ "$cache" == true ]; then
        docker run --rm --net=host --name=server mie zk mc mw ramcloud testbench2
    else
        docker run --rm --net=host --name=server mie zk mw ramcloud nocache testbench2
    fi
fi